#ifndef AUTOCHESS_CONFIG_H
#define AUTOCHESS_CONFIG_H

#define AUTOCHESS_MAX_BATTLE_UNITS 16
#define AUTOCHESS_DEMO_TEAM_SIZE 3
#define AUTOCHESS_MAX_BATTLE_ROUNDS 100
#define AUTOCHESS_BOARD_ROWS 8
#define AUTOCHESS_BOARD_COLS 7
#define AUTOCHESS_BENCH_SIZE 9
#define AUTOCHESS_MAX_PLAYER_UNITS 32

#endif
