#ifndef AUTOCHESS_CONFIG_H
#define AUTOCHESS_CONFIG_H

#define AUTOCHESS_MAX_BATTLE_UNITS 16
#define AUTOCHESS_DEMO_TEAM_SIZE 3
#define AUTOCHESS_MAX_BATTLE_ROUNDS 100
#define AUTOCHESS_BOARD_ROWS 8
#define AUTOCHESS_BOARD_COLS 7
#define AUTOCHESS_BENCH_SIZE 9
#define AUTOCHESS_MAX_PLAYER_UNITS 32
#define AUTOCHESS_SHOP_SIZE 5
#define AUTOCHESS_BASE_ROUND_INCOME 5
#define AUTOCHESS_MAX_INTEREST 5
#define AUTOCHESS_REFRESH_COST 2
#define AUTOCHESS_BUY_EXP_COST 4
#define AUTOCHESS_BUY_EXP_AMOUNT 4
#define AUTOCHESS_MAX_LEVEL 8
#define AUTOCHESS_EXP_PER_LEVEL 4
#define AUTOCHESS_MAX_STAR 3

#endif
